version: "3"
services:
  server_authetication:
    build:
      context: .
      dockerfile: ./docker/django.dockerfile
    tty: true
    ports:
      - "8000:8000"
    command: >
      bash -c 'python manage.py runserver 0.0.0.0:8000'
    restart: unless-stopped
    networks:
      - sd-network
    volumes:
      - ./app/auth_project/:/app/
  server_business:
    build:
      context: .
      dockerfile: ./docker/django.dockerfile
    tty: true
    ports:
      - "8050:8050"
    command: >
      bash -c 'python manage.py runserver 0.0.0.0:8050'
    restart: unless-stopped
    networks:
      - sd-network
    volumes:
      - ./app/business_project/:/app/

  db:
    image: postgres:14.2
    ports:
      - "5434:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - sd-network

networks:
  sd-network:
    name: sd-network

volumes:
  postgres_data: